apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    name: {{ .Values.namespace.name }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.namespace.name }}-quota
  namespace: {{ .Values.namespace.name }}
spec:
  hard:
    requests.cpu: {{ .Values.namespace.quota.requests.cpu }}
    requests.memory: {{ .Values.namespace.quota.requests.memory }}
    limits.cpu: {{ .Values.namespace.quota.limits.cpu }}
    limits.memory: {{ .Values.namespace.quota.limits.memory }}
    pods: {{ .Values.namespace.quota.pods }}
    services: {{ .Values.namespace.quota.services }}
    persistentvolumeclaims: {{ .Values.namespace.quota.persistentvolumeclaims }}
    configmaps: {{ .Values.namespace.quota.configmaps }}
    secrets: {{ .Values.namespace.quota.secrets }}
    replicationcontrollers: {{ .Values.namespace.quota.replicationcontrollers }}
    resourcequotas: {{ .Values.namespace.quota.resourcequotas }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace.name }}-limits
  namespace: {{ .Values.namespace.name }}
spec:
  limits:
    - max:
        cpu: {{ .Values.namespace.limits.max.cpu }}
        memory: {{ .Values.namespace.limits.max.memory }}
      min:
        cpu: {{ .Values.namespace.limits.min.cpu }}
        memory: {{ .Values.namespace.limits.min.memory }}
      type: Container