# templates/growthbook-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: growthbook
spec:
  type: {{ .Values.growthbook.service.type }}
  ports:
    {{- range .Values.growthbook.service.ports }}
      - port: {{ .port }}
        targetPort: {{ .targetPort }}
        protocol: {{ .protocol | default "TCP" }}
        name: {{ .name }}
    {{- end }}
  selector:
    app: growthbook